Rails.application.routes.draw do
  root 'homepage#home'
  get '/museum', to: 'homepage#museum', as: 'museum'
  get '/materials', to: 'homepage#materials', as: 'materials'
  get '/teachers', to: 'homepage#teachers', as: 'teachers'
  get '/history', to: 'homepage#history', as: 'history'
  get 'homepage/profile_list'
  get 'homepage/exit_profile_list'
  get 'get_image/:path', to: 'homepage#get_image'
  get 'homepage/search'
  get '/admin', to: 'profile#admin_profile', as: 'admin'
  get '/profile', to: 'profile#profile', as: 'profile'
  get '/users/edit/:id', to: 'profile#edit'
  get '/add_teacher', to: 'profile#add_teacher', as: 'add_teacher'
  get '/profile/edit_teacher/:id', to: 'profile#edit_teacher'
  get 'list_teachers', to: 'profile#list_teachers', as: 'list_teachers'
  get '/change_password', to: 'profile#change_password'
  patch '/change_password/:id', to: 'profile#password_update'
  post '/create_teacher', to: 'profile#create_user', as: 'create_user'
  put '/update_teacher/:id', to: 'profile#update_teacher'
  patch '/set_admin/:id', to: 'profile#set_admin'
  get 'profile/change/:id', to: 'profile#change'
  patch '/profile/update/:field/:id', to: 'profile#update'
  post '/profile/destroy/:id', to: 'profile#destroy'
  delete '/profile/destroy/:id', to: 'profile#confirm_destroy'
  post '/profile/cancel_destroy/:id', to: 'profile#cancel_destroy'
  get '/requests', to: 'request#admin', as: 'requests'
  get '/already_read', to: 'request#already_read'
  get '/send_request', to: 'request#send_request', as: 'send_request'
  get '/add_files', to: 'request#add_files', as: 'add_files'
  get '/request/change/:id', to: 'request#change_request'
  post '/request/change/:id', to: 'request#change'
  get '/my_requests', to: 'request#user_requests'
  post '/request/create'
  post '/request/read/:id', to: 'request#read'
  get '/storage', to: 'storage#index'
  post '/storage/:type', to: 'storage#change'
  devise_for :users, path_name: { sign_up: 'registrations/new' }, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
