:scheduler:
  :schedule:
    delete_users_without_confirmation:
      cron: "0 0 * * 7"
      class: 'DeleteUsersWithoutConfirmationScheduler'
      queue: default

development:
  :concurrency: 7
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 15 %>
:queues:
  - default
:max_retries: 3